//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::favorites::Entity as Favorites;
pub use super::likes::Entity as Likes;
pub use super::users::Entity as Users;
