//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19
//! + 手动扩展 company/location/website/social_links 字段

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub username: String,
    #[sea_orm(unique)]
    pub email: String,
    pub password_hash: String,
    pub display_name: String,
    #[sea_orm(column_type = "Text")]
    pub avatar_url: String,
    #[sea_orm(column_type = "Text")]
    pub bio: String,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    // ── 社交链接扩展字段 ──
    pub company: String,
    pub location: String,
    pub website: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub social_links: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::articles::Entity")]
    Articles,
}

impl Related<super::articles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Articles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
