// @generated by scripts/gen-proto-mod.sh — DO NOT EDIT
// Proto 生成代码模块
// prost 生成的 .rs 文件末尾会自动 include 对应的 .tonic.rs 文件
// 因此只需 include prost 文件即可同时获得类型定义和 gRPC client/server

#[allow(clippy::all, clippy::pedantic)]
pub mod luhanxin {
pub mod community {
pub mod v1 {
    include!("luhanxin/community/v1/luhanxin.community.v1.rs");
}
}
}

// Re-export：扁平化导出，使用时直接 `use shared::proto::XxxRequest` 即可
pub use luhanxin::community::v1::*;
