// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/article.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PaginationRequest, PaginationResponse } from "./common_pb";
import { file_luhanxin_community_v1_common } from "./common_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/article.proto.
 */
export const file_luhanxin_community_v1_article: GenFile = /*@__PURE__*/
  fileDesc("CiNsdWhhbnhpbi9jb21tdW5pdHkvdjEvYXJ0aWNsZS5wcm90bxIVbHVoYW54aW4uY29tbXVuaXR5LnYxIicKEUdldEFydGljbGVSZXF1ZXN0EhIKCmFydGljbGVfaWQYASABKAkiRQoSR2V0QXJ0aWNsZVJlc3BvbnNlEi8KB2FydGljbGUYASABKAsyHi5sdWhhbnhpbi5jb21tdW5pdHkudjEuQXJ0aWNsZSJmChNMaXN0QXJ0aWNsZXNSZXF1ZXN0EjwKCnBhZ2luYXRpb24YASABKAsyKC5sdWhhbnhpbi5jb21tdW5pdHkudjEuUGFnaW5hdGlvblJlcXVlc3QSEQoJYXV0aG9yX2lkGAIgASgJIocBChRMaXN0QXJ0aWNsZXNSZXNwb25zZRIwCghhcnRpY2xlcxgBIAMoCzIeLmx1aGFueGluLmNvbW11bml0eS52MS5BcnRpY2xlEj0KCnBhZ2luYXRpb24YAiABKAsyKS5sdWhhbnhpbi5jb21tdW5pdHkudjEuUGFnaW5hdGlvblJlc3BvbnNlIuUCCgdBcnRpY2xlEgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEgwKBHNsdWcYAyABKAkSDwoHc3VtbWFyeRgEIAEoCRIPCgdjb250ZW50GAUgASgJEhEKCWF1dGhvcl9pZBgGIAEoCRIMCgR0YWdzGAcgAygJEhIKCnZpZXdfY291bnQYCCABKAUSEgoKbGlrZV9jb3VudBgJIAEoBRI0CgZzdGF0dXMYCiABKA4yJC5sdWhhbnhpbi5jb21tdW5pdHkudjEuQXJ0aWNsZVN0YXR1cxIuCgpjcmVhdGVkX2F0GAsgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAwgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIwCgxwdWJsaXNoZWRfYXQYDSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wKoQBCg1BcnRpY2xlU3RhdHVzEh4KGkFSVElDTEVfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGAoUQVJUSUNMRV9TVEFUVVNfRFJBRlQQARIcChhBUlRJQ0xFX1NUQVRVU19QVUJMSVNIRUQQAhIbChdBUlRJQ0xFX1NUQVRVU19BUkNISVZFRBADMtwBCg5BcnRpY2xlU2VydmljZRJhCgpHZXRBcnRpY2xlEigubHVoYW54aW4uY29tbXVuaXR5LnYxLkdldEFydGljbGVSZXF1ZXN0GikubHVoYW54aW4uY29tbXVuaXR5LnYxLkdldEFydGljbGVSZXNwb25zZRJnCgxMaXN0QXJ0aWNsZXMSKi5sdWhhbnhpbi5jb21tdW5pdHkudjEuTGlzdEFydGljbGVzUmVxdWVzdBorLmx1aGFueGluLmNvbW11bml0eS52MS5MaXN0QXJ0aWNsZXNSZXNwb25zZWIGcHJvdG8z", [file_google_protobuf_timestamp, file_luhanxin_community_v1_common]);

/**
 * 获取文章请求
 *
 * @generated from message luhanxin.community.v1.GetArticleRequest
 */
export type GetArticleRequest = Message<"luhanxin.community.v1.GetArticleRequest"> & {
  /**
   * 文章 ID
   *
   * @generated from field: string article_id = 1;
   */
  articleId: string;
};

/**
 * Describes the message luhanxin.community.v1.GetArticleRequest.
 * Use `create(GetArticleRequestSchema)` to create a new message.
 */
export const GetArticleRequestSchema: GenMessage<GetArticleRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_article, 0);

/**
 * 获取文章响应
 *
 * @generated from message luhanxin.community.v1.GetArticleResponse
 */
export type GetArticleResponse = Message<"luhanxin.community.v1.GetArticleResponse"> & {
  /**
   * 文章详情
   *
   * @generated from field: luhanxin.community.v1.Article article = 1;
   */
  article?: Article;
};

/**
 * Describes the message luhanxin.community.v1.GetArticleResponse.
 * Use `create(GetArticleResponseSchema)` to create a new message.
 */
export const GetArticleResponseSchema: GenMessage<GetArticleResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_article, 1);

/**
 * 获取文章列表请求
 *
 * @generated from message luhanxin.community.v1.ListArticlesRequest
 */
export type ListArticlesRequest = Message<"luhanxin.community.v1.ListArticlesRequest"> & {
  /**
   * 分页参数
   *
   * @generated from field: luhanxin.community.v1.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * 可选：按作者筛选
   *
   * @generated from field: string author_id = 2;
   */
  authorId: string;
};

/**
 * Describes the message luhanxin.community.v1.ListArticlesRequest.
 * Use `create(ListArticlesRequestSchema)` to create a new message.
 */
export const ListArticlesRequestSchema: GenMessage<ListArticlesRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_article, 2);

/**
 * 获取文章列表响应
 *
 * @generated from message luhanxin.community.v1.ListArticlesResponse
 */
export type ListArticlesResponse = Message<"luhanxin.community.v1.ListArticlesResponse"> & {
  /**
   * 文章列表
   *
   * @generated from field: repeated luhanxin.community.v1.Article articles = 1;
   */
  articles: Article[];

  /**
   * 分页元数据
   *
   * @generated from field: luhanxin.community.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message luhanxin.community.v1.ListArticlesResponse.
 * Use `create(ListArticlesResponseSchema)` to create a new message.
 */
export const ListArticlesResponseSchema: GenMessage<ListArticlesResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_article, 3);

/**
 * 文章信息
 *
 * @generated from message luhanxin.community.v1.Article
 */
export type Article = Message<"luhanxin.community.v1.Article"> & {
  /**
   * 文章唯一标识
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 文章标题
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * URL slug
   *
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * 文章摘要
   *
   * @generated from field: string summary = 4;
   */
  summary: string;

  /**
   * 文章内容 (Markdown)
   *
   * @generated from field: string content = 5;
   */
  content: string;

  /**
   * 作者 ID
   *
   * @generated from field: string author_id = 6;
   */
  authorId: string;

  /**
   * 标签列表
   *
   * @generated from field: repeated string tags = 7;
   */
  tags: string[];

  /**
   * 浏览次数
   *
   * @generated from field: int32 view_count = 8;
   */
  viewCount: number;

  /**
   * 点赞次数
   *
   * @generated from field: int32 like_count = 9;
   */
  likeCount: number;

  /**
   * 文章状态
   *
   * @generated from field: luhanxin.community.v1.ArticleStatus status = 10;
   */
  status: ArticleStatus;

  /**
   * 创建时间
   *
   * @generated from field: google.protobuf.Timestamp created_at = 11;
   */
  createdAt?: Timestamp;

  /**
   * 更新时间
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 12;
   */
  updatedAt?: Timestamp;

  /**
   * 发布时间
   *
   * @generated from field: google.protobuf.Timestamp published_at = 13;
   */
  publishedAt?: Timestamp;
};

/**
 * Describes the message luhanxin.community.v1.Article.
 * Use `create(ArticleSchema)` to create a new message.
 */
export const ArticleSchema: GenMessage<Article> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_article, 4);

/**
 * 文章状态枚举
 *
 * @generated from enum luhanxin.community.v1.ArticleStatus
 */
export enum ArticleStatus {
  /**
   * @generated from enum value: ARTICLE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ARTICLE_STATUS_DRAFT = 1;
   */
  DRAFT = 1,

  /**
   * @generated from enum value: ARTICLE_STATUS_PUBLISHED = 2;
   */
  PUBLISHED = 2,

  /**
   * @generated from enum value: ARTICLE_STATUS_ARCHIVED = 3;
   */
  ARCHIVED = 3,
}

/**
 * Describes the enum luhanxin.community.v1.ArticleStatus.
 */
export const ArticleStatusSchema: GenEnum<ArticleStatus> = /*@__PURE__*/
  enumDesc(file_luhanxin_community_v1_article, 0);

/**
 * 文章服务
 *
 * @generated from service luhanxin.community.v1.ArticleService
 */
export const ArticleService: GenService<{
  /**
   * 获取文章详情
   *
   * @generated from rpc luhanxin.community.v1.ArticleService.GetArticle
   */
  getArticle: {
    methodKind: "unary";
    input: typeof GetArticleRequestSchema;
    output: typeof GetArticleResponseSchema;
  },
  /**
   * 获取文章列表
   *
   * @generated from rpc luhanxin.community.v1.ArticleService.ListArticles
   */
  listArticles: {
    methodKind: "unary";
    input: typeof ListArticlesRequestSchema;
    output: typeof ListArticlesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_luhanxin_community_v1_article, 0);

