// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/common.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/common.proto.
 */
export const file_luhanxin_community_v1_common: GenFile = /*@__PURE__*/
  fileDesc("CiJsdWhhbnhpbi9jb21tdW5pdHkvdjEvY29tbW9uLnByb3RvEhVsdWhhbnhpbi5jb21tdW5pdHkudjEiOgoRUGFnaW5hdGlvblJlcXVlc3QSEQoJcGFnZV9zaXplGAEgASgFEhIKCnBhZ2VfdG9rZW4YAiABKAkiQgoSUGFnaW5hdGlvblJlc3BvbnNlEhcKD25leHRfcGFnZV90b2tlbhgBIAEoCRITCgt0b3RhbF9jb3VudBgCIAEoBWIGcHJvdG8z");

/**
 * 分页请求参数
 *
 * @generated from message luhanxin.community.v1.PaginationRequest
 */
export type PaginationRequest = Message<"luhanxin.community.v1.PaginationRequest"> & {
  /**
   * 每页大小，默认 20，最大 100
   *
   * @generated from field: int32 page_size = 1;
   */
  pageSize: number;

  /**
   * 分页游标 token，首页为空
   *
   * @generated from field: string page_token = 2;
   */
  pageToken: string;
};

/**
 * Describes the message luhanxin.community.v1.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_common, 0);

/**
 * 分页响应元数据
 *
 * @generated from message luhanxin.community.v1.PaginationResponse
 */
export type PaginationResponse = Message<"luhanxin.community.v1.PaginationResponse"> & {
  /**
   * 下一页游标 token，为空表示无更多数据
   *
   * @generated from field: string next_page_token = 1;
   */
  nextPageToken: string;

  /**
   * 总记录数（可选，某些查询可能不返回）
   *
   * @generated from field: int32 total_count = 2;
   */
  totalCount: number;
};

/**
 * Describes the message luhanxin.community.v1.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_common, 1);

