// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/comment.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PaginationRequest, PaginationResponse } from "./common_pb";
import { file_luhanxin_community_v1_common } from "./common_pb";
import type { User } from "./user_pb";
import { file_luhanxin_community_v1_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/comment.proto.
 */
export const file_luhanxin_community_v1_comment: GenFile = /*@__PURE__*/
  fileDesc("CiNsdWhhbnhpbi9jb21tdW5pdHkvdjEvY29tbWVudC5wcm90bxIVbHVoYW54aW4uY29tbXVuaXR5LnYxImMKFENyZWF0ZUNvbW1lbnRSZXF1ZXN0EhIKCmFydGljbGVfaWQYASABKAkSDwoHY29udGVudBgCIAEoCRIRCglwYXJlbnRfaWQYAyABKAkSEwoLcmVwbHlfdG9faWQYBCABKAkiSAoVQ3JlYXRlQ29tbWVudFJlc3BvbnNlEi8KB2NvbW1lbnQYASABKAsyHi5sdWhhbnhpbi5jb21tdW5pdHkudjEuQ29tbWVudCJnChNMaXN0Q29tbWVudHNSZXF1ZXN0EhIKCmFydGljbGVfaWQYASABKAkSPAoKcGFnaW5hdGlvbhgCIAEoCzIoLmx1aGFueGluLmNvbW11bml0eS52MS5QYWdpbmF0aW9uUmVxdWVzdCKHAQoUTGlzdENvbW1lbnRzUmVzcG9uc2USMAoIY29tbWVudHMYASADKAsyHi5sdWhhbnhpbi5jb21tdW5pdHkudjEuQ29tbWVudBI9CgpwYWdpbmF0aW9uGAIgASgLMikubHVoYW54aW4uY29tbXVuaXR5LnYxLlBhZ2luYXRpb25SZXNwb25zZSIqChREZWxldGVDb21tZW50UmVxdWVzdBISCgpjb21tZW50X2lkGAEgASgJIhcKFURlbGV0ZUNvbW1lbnRSZXNwb25zZSL7AgoHQ29tbWVudBIKCgJpZBgBIAEoCRISCgphcnRpY2xlX2lkGAIgASgJEhEKCWF1dGhvcl9pZBgDIAEoCRIPCgdjb250ZW50GAQgASgJEhEKCXBhcmVudF9pZBgFIAEoCRITCgtyZXBseV90b19pZBgGIAEoCRIQCghtZW50aW9ucxgHIAMoCRIuCgpjcmVhdGVkX2F0GAggASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIrCgZhdXRob3IYCiABKAsyGy5sdWhhbnhpbi5jb21tdW5pdHkudjEuVXNlchI0Cg9yZXBseV90b19hdXRob3IYCyABKAsyGy5sdWhhbnhpbi5jb21tdW5pdHkudjEuVXNlchIvCgdyZXBsaWVzGAwgAygLMh4ubHVoYW54aW4uY29tbXVuaXR5LnYxLkNvbW1lbnQy0QIKDkNvbW1lbnRTZXJ2aWNlEmoKDUNyZWF0ZUNvbW1lbnQSKy5sdWhhbnhpbi5jb21tdW5pdHkudjEuQ3JlYXRlQ29tbWVudFJlcXVlc3QaLC5sdWhhbnhpbi5jb21tdW5pdHkudjEuQ3JlYXRlQ29tbWVudFJlc3BvbnNlEmcKDExpc3RDb21tZW50cxIqLmx1aGFueGluLmNvbW11bml0eS52MS5MaXN0Q29tbWVudHNSZXF1ZXN0GisubHVoYW54aW4uY29tbXVuaXR5LnYxLkxpc3RDb21tZW50c1Jlc3BvbnNlEmoKDURlbGV0ZUNvbW1lbnQSKy5sdWhhbnhpbi5jb21tdW5pdHkudjEuRGVsZXRlQ29tbWVudFJlcXVlc3QaLC5sdWhhbnhpbi5jb21tdW5pdHkudjEuRGVsZXRlQ29tbWVudFJlc3BvbnNlYgZwcm90bzM", [file_google_protobuf_timestamp, file_luhanxin_community_v1_common, file_luhanxin_community_v1_user]);

/**
 * @generated from message luhanxin.community.v1.CreateCommentRequest
 */
export type CreateCommentRequest = Message<"luhanxin.community.v1.CreateCommentRequest"> & {
  /**
   * 文章 ID
   *
   * @generated from field: string article_id = 1;
   */
  articleId: string;

  /**
   * 评论内容（支持 emoji unicode + @username 文本）
   *
   * @generated from field: string content = 2;
   */
  content: string;

  /**
   * 顶级评论 ID（为空表示发表顶级评论，非空表示二级回复）
   *
   * @generated from field: string parent_id = 3;
   */
  parentId: string;

  /**
   * 被回复的评论 ID（为空表示直接回复顶级评论，非空表示回复某条二级评论）
   *
   * @generated from field: string reply_to_id = 4;
   */
  replyToId: string;
};

/**
 * Describes the message luhanxin.community.v1.CreateCommentRequest.
 * Use `create(CreateCommentRequestSchema)` to create a new message.
 */
export const CreateCommentRequestSchema: GenMessage<CreateCommentRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 0);

/**
 * @generated from message luhanxin.community.v1.CreateCommentResponse
 */
export type CreateCommentResponse = Message<"luhanxin.community.v1.CreateCommentResponse"> & {
  /**
   * 创建后的评论
   *
   * @generated from field: luhanxin.community.v1.Comment comment = 1;
   */
  comment?: Comment;
};

/**
 * Describes the message luhanxin.community.v1.CreateCommentResponse.
 * Use `create(CreateCommentResponseSchema)` to create a new message.
 */
export const CreateCommentResponseSchema: GenMessage<CreateCommentResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 1);

/**
 * @generated from message luhanxin.community.v1.ListCommentsRequest
 */
export type ListCommentsRequest = Message<"luhanxin.community.v1.ListCommentsRequest"> & {
  /**
   * 文章 ID
   *
   * @generated from field: string article_id = 1;
   */
  articleId: string;

  /**
   * 分页参数
   *
   * @generated from field: luhanxin.community.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message luhanxin.community.v1.ListCommentsRequest.
 * Use `create(ListCommentsRequestSchema)` to create a new message.
 */
export const ListCommentsRequestSchema: GenMessage<ListCommentsRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 2);

/**
 * @generated from message luhanxin.community.v1.ListCommentsResponse
 */
export type ListCommentsResponse = Message<"luhanxin.community.v1.ListCommentsResponse"> & {
  /**
   * 顶级评论列表（每条包含 replies 子回复）
   *
   * @generated from field: repeated luhanxin.community.v1.Comment comments = 1;
   */
  comments: Comment[];

  /**
   * 分页元数据
   *
   * @generated from field: luhanxin.community.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message luhanxin.community.v1.ListCommentsResponse.
 * Use `create(ListCommentsResponseSchema)` to create a new message.
 */
export const ListCommentsResponseSchema: GenMessage<ListCommentsResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 3);

/**
 * @generated from message luhanxin.community.v1.DeleteCommentRequest
 */
export type DeleteCommentRequest = Message<"luhanxin.community.v1.DeleteCommentRequest"> & {
  /**
   * 评论 ID
   *
   * @generated from field: string comment_id = 1;
   */
  commentId: string;
};

/**
 * Describes the message luhanxin.community.v1.DeleteCommentRequest.
 * Use `create(DeleteCommentRequestSchema)` to create a new message.
 */
export const DeleteCommentRequestSchema: GenMessage<DeleteCommentRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 4);

/**
 * 空响应，删除成功
 *
 * @generated from message luhanxin.community.v1.DeleteCommentResponse
 */
export type DeleteCommentResponse = Message<"luhanxin.community.v1.DeleteCommentResponse"> & {
};

/**
 * Describes the message luhanxin.community.v1.DeleteCommentResponse.
 * Use `create(DeleteCommentResponseSchema)` to create a new message.
 */
export const DeleteCommentResponseSchema: GenMessage<DeleteCommentResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 5);

/**
 * 评论信息
 *
 * @generated from message luhanxin.community.v1.Comment
 */
export type Comment = Message<"luhanxin.community.v1.Comment"> & {
  /**
   * 评论唯一标识
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 文章 ID
   *
   * @generated from field: string article_id = 2;
   */
  articleId: string;

  /**
   * 作者 ID
   *
   * @generated from field: string author_id = 3;
   */
  authorId: string;

  /**
   * 评论内容
   *
   * @generated from field: string content = 4;
   */
  content: string;

  /**
   * 顶级评论 ID（空 = 顶级评论）
   *
   * @generated from field: string parent_id = 5;
   */
  parentId: string;

  /**
   * 被回复评论 ID（空 = 直接回复顶级评论）
   *
   * @generated from field: string reply_to_id = 6;
   */
  replyToId: string;

  /**
   * 被 @ 的用户名列表（后端从 content 解析）
   *
   * @generated from field: repeated string mentions = 7;
   */
  mentions: string[];

  /**
   * 创建时间
   *
   * @generated from field: google.protobuf.Timestamp created_at = 8;
   */
  createdAt?: Timestamp;

  /**
   * 更新时间
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 9;
   */
  updatedAt?: Timestamp;

  /**
   * 作者信息（由服务端填充）
   *
   * @generated from field: luhanxin.community.v1.User author = 10;
   */
  author?: User;

  /**
   * 被回复者信息（二级回复时填充，方便显示「回复 @xxx」）
   *
   * @generated from field: luhanxin.community.v1.User reply_to_author = 11;
   */
  replyToAuthor?: User;

  /**
   * 子回复列表（仅顶级评论填充）
   *
   * @generated from field: repeated luhanxin.community.v1.Comment replies = 12;
   */
  replies: Comment[];
};

/**
 * Describes the message luhanxin.community.v1.Comment.
 * Use `create(CommentSchema)` to create a new message.
 */
export const CommentSchema: GenMessage<Comment> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_comment, 6);

/**
 * 评论服务
 *
 * @generated from service luhanxin.community.v1.CommentService
 */
export const CommentService: GenService<{
  /**
   * 创建评论（需认证）
   *
   * @generated from rpc luhanxin.community.v1.CommentService.CreateComment
   */
  createComment: {
    methodKind: "unary";
    input: typeof CreateCommentRequestSchema;
    output: typeof CreateCommentResponseSchema;
  },
  /**
   * 获取文章评论列表（公开，返回二级嵌套结构）
   *
   * @generated from rpc luhanxin.community.v1.CommentService.ListComments
   */
  listComments: {
    methodKind: "unary";
    input: typeof ListCommentsRequestSchema;
    output: typeof ListCommentsResponseSchema;
  },
  /**
   * 删除评论（需认证，仅作者）
   *
   * @generated from rpc luhanxin.community.v1.CommentService.DeleteComment
   */
  deleteComment: {
    methodKind: "unary";
    input: typeof DeleteCommentRequestSchema;
    output: typeof DeleteCommentResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_luhanxin_community_v1_comment, 0);

