// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/event.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/event.proto.
 */
export const file_luhanxin_community_v1_event: GenFile = /*@__PURE__*/
  fileDesc("CiFsdWhhbnhpbi9jb21tdW5pdHkvdjEvZXZlbnQucHJvdG8SFWx1aGFueGluLmNvbW11bml0eS52MSKnAgoNRXZlbnRFbnZlbG9wZRIQCghldmVudF9pZBgBIAEoCRISCgpldmVudF90eXBlGAIgASgJEg4KBnNvdXJjZRgDIAEoCRItCgl0aW1lc3RhbXAYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEiUKB3BheWxvYWQYBSABKAsyFC5nb29nbGUucHJvdG9idWYuQW55EkQKCG1ldGFkYXRhGAYgAygLMjIubHVoYW54aW4uY29tbXVuaXR5LnYxLkV2ZW50RW52ZWxvcGUuTWV0YWRhdGFFbnRyeRITCgtyZXRyeV9jb3VudBgHIAEoBRovCg1NZXRhZGF0YUVudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEivQEKDFJldHJ5UmVxdWVzdBISCgpyZXF1ZXN0X2lkGAEgASgJEhYKDnRhcmdldF9zZXJ2aWNlGAIgASgJEg4KBm1ldGhvZBgDIAEoCRIXCg9yZXF1ZXN0X3BheWxvYWQYBCABKAwSEwoLcmV0cnlfY291bnQYBSABKAUSEwoLbWF4X3JldHJpZXMYBiABKAUSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBiBnByb3RvMw", [file_google_protobuf_any, file_google_protobuf_timestamp]);

/**
 * 事件信封 — 所有异步事件的标准包装
 *
 * 通过 NATS 发布/订阅，消息体为此消息的 Protobuf 二进制编码。
 * Subject 命名：luhanxin.events.<domain>.<action>
 *
 * @generated from message luhanxin.community.v1.EventEnvelope
 */
export type EventEnvelope = Message<"luhanxin.community.v1.EventEnvelope"> & {
  /**
   * 唯一事件 ID (UUID v4)
   *
   * @generated from field: string event_id = 1;
   */
  eventId: string;

  /**
   * 事件类型，如 "user.created"、"article.published"
   *
   * @generated from field: string event_type = 2;
   */
  eventType: string;

  /**
   * 来源服务，如 "gateway"、"svc-user"
   *
   * @generated from field: string source = 3;
   */
  source: string;

  /**
   * 事件产生时间
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * 事件体（具体的 Proto 消息，使用 Any 包装）
   *
   * @generated from field: google.protobuf.Any payload = 5;
   */
  payload?: Any;

  /**
   * 元数据（trace_id、correlation_id、user_id 等）
   *
   * @generated from field: map<string, string> metadata = 6;
   */
  metadata: { [key: string]: string };

  /**
   * 重试次数（初始为 0）
   *
   * @generated from field: int32 retry_count = 7;
   */
  retryCount: number;
};

/**
 * Describes the message luhanxin.community.v1.EventEnvelope.
 * Use `create(EventEnvelopeSchema)` to create a new message.
 */
export const EventEnvelopeSchema: GenMessage<EventEnvelope> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_event, 0);

/**
 * Gateway 异步重试信封
 *
 * 当 Gateway 调用下游 RPC 失败（UNAVAILABLE / DEADLINE_EXCEEDED）时，
 * 将原始请求打包为 RetryRequest 写入 NATS 重试队列。
 * Subject 命名：luhanxin.retry.<service>.<method>
 *
 * @generated from message luhanxin.community.v1.RetryRequest
 */
export type RetryRequest = Message<"luhanxin.community.v1.RetryRequest"> & {
  /**
   * 请求唯一标识 (UUID v4)
   *
   * @generated from field: string request_id = 1;
   */
  requestId: string;

  /**
   * 目标服务名，如 "svc-user"
   *
   * @generated from field: string target_service = 2;
   */
  targetService: string;

  /**
   * gRPC 方法全名，如 "luhanxin.community.v1.UserService/GetUser"
   *
   * @generated from field: string method = 3;
   */
  method: string;

  /**
   * 原始请求的 Protobuf 序列化字节
   *
   * @generated from field: bytes request_payload = 4;
   */
  requestPayload: Uint8Array;

  /**
   * 已重试次数
   *
   * @generated from field: int32 retry_count = 5;
   */
  retryCount: number;

  /**
   * 最大重试次数
   *
   * @generated from field: int32 max_retries = 6;
   */
  maxRetries: number;

  /**
   * 首次入队时间
   *
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message luhanxin.community.v1.RetryRequest.
 * Use `create(RetryRequestSchema)` to create a new message.
 */
export const RetryRequestSchema: GenMessage<RetryRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_event, 1);

