// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/search.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { PaginationRequest, PaginationResponse } from "./common_pb";
import { file_luhanxin_community_v1_common } from "./common_pb";
import type { User } from "./user_pb";
import { file_luhanxin_community_v1_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/search.proto.
 */
export const file_luhanxin_community_v1_search: GenFile = /*@__PURE__*/
  fileDesc("CiJsdWhhbnhpbi9jb21tdW5pdHkvdjEvc2VhcmNoLnByb3RvEhVsdWhhbnhpbi5jb21tdW5pdHkudjEiZAoVU2VhcmNoQXJ0aWNsZXNSZXF1ZXN0Eg0KBXF1ZXJ5GAEgASgJEjwKCnBhZ2luYXRpb24YAiABKAsyKC5sdWhhbnhpbi5jb21tdW5pdHkudjEuUGFnaW5hdGlvblJlcXVlc3QijgEKFlNlYXJjaEFydGljbGVzUmVzcG9uc2USNQoEaGl0cxgBIAMoCzInLmx1aGFueGluLmNvbW11bml0eS52MS5TZWFyY2hBcnRpY2xlSGl0Ej0KCnBhZ2luYXRpb24YAiABKAsyKS5sdWhhbnhpbi5jb21tdW5pdHkudjEuUGFnaW5hdGlvblJlc3BvbnNlIvQBChBTZWFyY2hBcnRpY2xlSGl0EgoKAmlkGAEgASgJEg0KBXRpdGxlGAIgASgJEg8KB3N1bW1hcnkYAyABKAkSEQoJYXV0aG9yX2lkGAQgASgJEgwKBHRhZ3MYBSADKAkSEgoKdmlld19jb3VudBgGIAEoBRISCgpsaWtlX2NvdW50GAcgASgFEjAKDHB1Ymxpc2hlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKwoGYXV0aG9yGAkgASgLMhsubHVoYW54aW4uY29tbXVuaXR5LnYxLlVzZXISDAoEc2x1ZxgKIAEoCSJhChJTZWFyY2hVc2Vyc1JlcXVlc3QSDQoFcXVlcnkYASABKAkSPAoKcGFnaW5hdGlvbhgCIAEoCzIoLmx1aGFueGluLmNvbW11bml0eS52MS5QYWdpbmF0aW9uUmVxdWVzdCKIAQoTU2VhcmNoVXNlcnNSZXNwb25zZRIyCgRoaXRzGAEgAygLMiQubHVoYW54aW4uY29tbXVuaXR5LnYxLlNlYXJjaFVzZXJIaXQSPQoKcGFnaW5hdGlvbhgCIAEoCzIpLmx1aGFueGluLmNvbW11bml0eS52MS5QYWdpbmF0aW9uUmVzcG9uc2UiZAoNU2VhcmNoVXNlckhpdBIKCgJpZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSEgoKYXZhdGFyX3VybBgEIAEoCRILCgNiaW8YBSABKAky5AEKDVNlYXJjaFNlcnZpY2USbQoOU2VhcmNoQXJ0aWNsZXMSLC5sdWhhbnhpbi5jb21tdW5pdHkudjEuU2VhcmNoQXJ0aWNsZXNSZXF1ZXN0Gi0ubHVoYW54aW4uY29tbXVuaXR5LnYxLlNlYXJjaEFydGljbGVzUmVzcG9uc2USZAoLU2VhcmNoVXNlcnMSKS5sdWhhbnhpbi5jb21tdW5pdHkudjEuU2VhcmNoVXNlcnNSZXF1ZXN0GioubHVoYW54aW4uY29tbXVuaXR5LnYxLlNlYXJjaFVzZXJzUmVzcG9uc2ViBnByb3RvMw", [file_google_protobuf_timestamp, file_luhanxin_community_v1_common, file_luhanxin_community_v1_user]);

/**
 * @generated from message luhanxin.community.v1.SearchArticlesRequest
 */
export type SearchArticlesRequest = Message<"luhanxin.community.v1.SearchArticlesRequest"> & {
  /**
   * 搜索关键词（不能为空）
   *
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * 分页参数
   *
   * @generated from field: luhanxin.community.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message luhanxin.community.v1.SearchArticlesRequest.
 * Use `create(SearchArticlesRequestSchema)` to create a new message.
 */
export const SearchArticlesRequestSchema: GenMessage<SearchArticlesRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 0);

/**
 * @generated from message luhanxin.community.v1.SearchArticlesResponse
 */
export type SearchArticlesResponse = Message<"luhanxin.community.v1.SearchArticlesResponse"> & {
  /**
   * 搜索结果列表
   *
   * @generated from field: repeated luhanxin.community.v1.SearchArticleHit hits = 1;
   */
  hits: SearchArticleHit[];

  /**
   * 分页元数据
   *
   * @generated from field: luhanxin.community.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message luhanxin.community.v1.SearchArticlesResponse.
 * Use `create(SearchArticlesResponseSchema)` to create a new message.
 */
export const SearchArticlesResponseSchema: GenMessage<SearchArticlesResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 1);

/**
 * 文章搜索结果
 *
 * @generated from message luhanxin.community.v1.SearchArticleHit
 */
export type SearchArticleHit = Message<"luhanxin.community.v1.SearchArticleHit"> & {
  /**
   * 文章 ID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 文章标题（可能包含 <em> 高亮标签）
   *
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * 文章摘要（可能包含 <em> 高亮标签）
   *
   * @generated from field: string summary = 3;
   */
  summary: string;

  /**
   * 作者 ID
   *
   * @generated from field: string author_id = 4;
   */
  authorId: string;

  /**
   * 标签列表
   *
   * @generated from field: repeated string tags = 5;
   */
  tags: string[];

  /**
   * 浏览次数
   *
   * @generated from field: int32 view_count = 6;
   */
  viewCount: number;

  /**
   * 点赞次数
   *
   * @generated from field: int32 like_count = 7;
   */
  likeCount: number;

  /**
   * 发布时间
   *
   * @generated from field: google.protobuf.Timestamp published_at = 8;
   */
  publishedAt?: Timestamp;

  /**
   * 作者信息（由 Gateway BFF 层聚合填充）
   *
   * @generated from field: luhanxin.community.v1.User author = 9;
   */
  author?: User;

  /**
   * URL slug
   *
   * @generated from field: string slug = 10;
   */
  slug: string;
};

/**
 * Describes the message luhanxin.community.v1.SearchArticleHit.
 * Use `create(SearchArticleHitSchema)` to create a new message.
 */
export const SearchArticleHitSchema: GenMessage<SearchArticleHit> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 2);

/**
 * @generated from message luhanxin.community.v1.SearchUsersRequest
 */
export type SearchUsersRequest = Message<"luhanxin.community.v1.SearchUsersRequest"> & {
  /**
   * 搜索关键词（不能为空）
   *
   * @generated from field: string query = 1;
   */
  query: string;

  /**
   * 分页参数
   *
   * @generated from field: luhanxin.community.v1.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest;
};

/**
 * Describes the message luhanxin.community.v1.SearchUsersRequest.
 * Use `create(SearchUsersRequestSchema)` to create a new message.
 */
export const SearchUsersRequestSchema: GenMessage<SearchUsersRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 3);

/**
 * @generated from message luhanxin.community.v1.SearchUsersResponse
 */
export type SearchUsersResponse = Message<"luhanxin.community.v1.SearchUsersResponse"> & {
  /**
   * 搜索结果列表
   *
   * @generated from field: repeated luhanxin.community.v1.SearchUserHit hits = 1;
   */
  hits: SearchUserHit[];

  /**
   * 分页元数据
   *
   * @generated from field: luhanxin.community.v1.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message luhanxin.community.v1.SearchUsersResponse.
 * Use `create(SearchUsersResponseSchema)` to create a new message.
 */
export const SearchUsersResponseSchema: GenMessage<SearchUsersResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 4);

/**
 * 用户搜索结果
 *
 * @generated from message luhanxin.community.v1.SearchUserHit
 */
export type SearchUserHit = Message<"luhanxin.community.v1.SearchUserHit"> & {
  /**
   * 用户 ID
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 用户名（可能包含 <em> 高亮标签）
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * 显示名称（可能包含 <em> 高亮标签）
   *
   * @generated from field: string display_name = 3;
   */
  displayName: string;

  /**
   * 头像 URL
   *
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * 个人简介
   *
   * @generated from field: string bio = 5;
   */
  bio: string;
};

/**
 * Describes the message luhanxin.community.v1.SearchUserHit.
 * Use `create(SearchUserHitSchema)` to create a new message.
 */
export const SearchUserHitSchema: GenMessage<SearchUserHit> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_search, 5);

/**
 * 搜索服务（Gateway BFF 层直接调用 Meilisearch）
 *
 * @generated from service luhanxin.community.v1.SearchService
 */
export const SearchService: GenService<{
  /**
   * 搜索文章（公开，支持中文分词 + 高亮）
   *
   * @generated from rpc luhanxin.community.v1.SearchService.SearchArticles
   */
  searchArticles: {
    methodKind: "unary";
    input: typeof SearchArticlesRequestSchema;
    output: typeof SearchArticlesResponseSchema;
  },
  /**
   * 搜索用户（公开）
   *
   * @generated from rpc luhanxin.community.v1.SearchService.SearchUsers
   */
  searchUsers: {
    methodKind: "unary";
    input: typeof SearchUsersRequestSchema;
    output: typeof SearchUsersResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_luhanxin_community_v1_search, 0);

