// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/upload.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/upload.proto.
 */
export const file_luhanxin_community_v1_upload: GenFile = /*@__PURE__*/
  fileDesc("CiJsdWhhbnhpbi9jb21tdW5pdHkvdjEvdXBsb2FkLnByb3RvEhVsdWhhbnhpbi5jb21tdW5pdHkudjEiKwoZR2V0VXBsb2FkU2lnbmF0dXJlUmVxdWVzdBIOCgZmb2xkZXIYASABKAkidwoaR2V0VXBsb2FkU2lnbmF0dXJlUmVzcG9uc2USEQoJc2lnbmF0dXJlGAEgASgJEhEKCXRpbWVzdGFtcBgCIAEoAxISCgpjbG91ZF9uYW1lGAMgASgJEg8KB2FwaV9rZXkYBCABKAkSDgoGZm9sZGVyGAUgASgJMooBCg1VcGxvYWRTZXJ2aWNlEnkKEkdldFVwbG9hZFNpZ25hdHVyZRIwLmx1aGFueGluLmNvbW11bml0eS52MS5HZXRVcGxvYWRTaWduYXR1cmVSZXF1ZXN0GjEubHVoYW54aW4uY29tbXVuaXR5LnYxLkdldFVwbG9hZFNpZ25hdHVyZVJlc3BvbnNlYgZwcm90bzM");

/**
 * @generated from message luhanxin.community.v1.GetUploadSignatureRequest
 */
export type GetUploadSignatureRequest = Message<"luhanxin.community.v1.GetUploadSignatureRequest"> & {
  /**
   * 上传目标文件夹（如 "avatars"、"covers"）
   *
   * @generated from field: string folder = 1;
   */
  folder: string;
};

/**
 * Describes the message luhanxin.community.v1.GetUploadSignatureRequest.
 * Use `create(GetUploadSignatureRequestSchema)` to create a new message.
 */
export const GetUploadSignatureRequestSchema: GenMessage<GetUploadSignatureRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_upload, 0);

/**
 * @generated from message luhanxin.community.v1.GetUploadSignatureResponse
 */
export type GetUploadSignatureResponse = Message<"luhanxin.community.v1.GetUploadSignatureResponse"> & {
  /**
   * Cloudinary SHA-1 签名
   *
   * @generated from field: string signature = 1;
   */
  signature: string;

  /**
   * 签名时间戳（Unix 秒）
   *
   * @generated from field: int64 timestamp = 2;
   */
  timestamp: bigint;

  /**
   * Cloudinary Cloud Name
   *
   * @generated from field: string cloud_name = 3;
   */
  cloudName: string;

  /**
   * Cloudinary API Key（公开，非 Secret）
   *
   * @generated from field: string api_key = 4;
   */
  apiKey: string;

  /**
   * 实际上传文件夹路径（含 user_id，如 "avatars/uuid-xxx"）
   *
   * @generated from field: string folder = 5;
   */
  folder: string;
};

/**
 * Describes the message luhanxin.community.v1.GetUploadSignatureResponse.
 * Use `create(GetUploadSignatureResponseSchema)` to create a new message.
 */
export const GetUploadSignatureResponseSchema: GenMessage<GetUploadSignatureResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_upload, 1);

/**
 * 上传服务（签名生成，实际上传走 REST multipart）
 *
 * @generated from service luhanxin.community.v1.UploadService
 */
export const UploadService: GenService<{
  /**
   * 获取 Cloudinary 上传签名（需认证）
   *
   * @generated from rpc luhanxin.community.v1.UploadService.GetUploadSignature
   */
  getUploadSignature: {
    methodKind: "unary";
    input: typeof GetUploadSignatureRequestSchema;
    output: typeof GetUploadSignatureResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_luhanxin_community_v1_upload, 0);

