// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file luhanxin/community/v1/user.proto (package luhanxin.community.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file luhanxin/community/v1/user.proto.
 */
export const file_luhanxin_community_v1_user: GenFile = /*@__PURE__*/
  fileDesc("CiBsdWhhbnhpbi9jb21tdW5pdHkvdjEvdXNlci5wcm90bxIVbHVoYW54aW4uY29tbXVuaXR5LnYxIiEKDkdldFVzZXJSZXF1ZXN0Eg8KB3VzZXJfaWQYASABKAkiPAoPR2V0VXNlclJlc3BvbnNlEikKBHVzZXIYASABKAsyGy5sdWhhbnhpbi5jb21tdW5pdHkudjEuVXNlciLKAQoEVXNlchIKCgJpZBgBIAEoCRIQCgh1c2VybmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIUCgxkaXNwbGF5X25hbWUYBCABKAkSEgoKYXZhdGFyX3VybBgFIAEoCRILCgNiaW8YBiABKAkSLgoKY3JlYXRlZF9hdBgHIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASLgoKdXBkYXRlZF9hdBgIIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXAyZwoLVXNlclNlcnZpY2USWAoHR2V0VXNlchIlLmx1aGFueGluLmNvbW11bml0eS52MS5HZXRVc2VyUmVxdWVzdBomLmx1aGFueGluLmNvbW11bml0eS52MS5HZXRVc2VyUmVzcG9uc2ViBnByb3RvMw", [file_google_protobuf_timestamp]);

/**
 * 获取用户请求
 *
 * @generated from message luhanxin.community.v1.GetUserRequest
 */
export type GetUserRequest = Message<"luhanxin.community.v1.GetUserRequest"> & {
  /**
   * 用户 ID
   *
   * @generated from field: string user_id = 1;
   */
  userId: string;
};

/**
 * Describes the message luhanxin.community.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_user, 0);

/**
 * 获取用户响应
 *
 * @generated from message luhanxin.community.v1.GetUserResponse
 */
export type GetUserResponse = Message<"luhanxin.community.v1.GetUserResponse"> & {
  /**
   * 用户信息
   *
   * @generated from field: luhanxin.community.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message luhanxin.community.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_user, 1);

/**
 * 用户信息
 *
 * @generated from message luhanxin.community.v1.User
 */
export type User = Message<"luhanxin.community.v1.User"> & {
  /**
   * 用户唯一标识
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * 用户名
   *
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * 邮箱地址
   *
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * 显示名称
   *
   * @generated from field: string display_name = 4;
   */
  displayName: string;

  /**
   * 头像 URL
   *
   * @generated from field: string avatar_url = 5;
   */
  avatarUrl: string;

  /**
   * 个人简介
   *
   * @generated from field: string bio = 6;
   */
  bio: string;

  /**
   * 创建时间
   *
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * 更新时间
   *
   * @generated from field: google.protobuf.Timestamp updated_at = 8;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message luhanxin.community.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_luhanxin_community_v1_user, 2);

/**
 * 用户服务
 *
 * @generated from service luhanxin.community.v1.UserService
 */
export const UserService: GenService<{
  /**
   * 获取用户信息
   *
   * @generated from rpc luhanxin.community.v1.UserService.GetUser
   */
  getUser: {
    methodKind: "unary";
    input: typeof GetUserRequestSchema;
    output: typeof GetUserResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_luhanxin_community_v1_user, 0);

