// @generated
// This file is @generated by prost-build.
/// 分页请求参数
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginationRequest {
    /// 每页大小，默认 20，最大 100
    #[prost(int32, tag = "1")]
    pub page_size: i32,
    /// 分页游标 token，首页为空
    #[prost(string, tag = "2")]
    pub page_token: ::prost::alloc::string::String,
}
/// 分页响应元数据
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PaginationResponse {
    /// 下一页游标 token，为空表示无更多数据
    #[prost(string, tag = "1")]
    pub next_page_token: ::prost::alloc::string::String,
    /// 总记录数（可选，某些查询可能不返回）
    #[prost(int32, tag = "2")]
    pub total_count: i32,
}
/// 获取文章请求
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetArticleRequest {
    /// 文章 ID
    #[prost(string, tag = "1")]
    pub article_id: ::prost::alloc::string::String,
}
/// 获取文章响应
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetArticleResponse {
    /// 文章详情
    #[prost(message, optional, tag = "1")]
    pub article: ::core::option::Option<Article>,
}
/// 获取文章列表请求
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListArticlesRequest {
    /// 分页参数
    #[prost(message, optional, tag = "1")]
    pub pagination: ::core::option::Option<PaginationRequest>,
    /// 可选：按作者筛选
    #[prost(string, tag = "2")]
    pub author_id: ::prost::alloc::string::String,
}
/// 获取文章列表响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListArticlesResponse {
    /// 文章列表
    #[prost(message, repeated, tag = "1")]
    pub articles: ::prost::alloc::vec::Vec<Article>,
    /// 分页元数据
    #[prost(message, optional, tag = "2")]
    pub pagination: ::core::option::Option<PaginationResponse>,
}
/// 文章信息
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Article {
    /// 文章唯一标识
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 文章标题
    #[prost(string, tag = "2")]
    pub title: ::prost::alloc::string::String,
    /// URL slug
    #[prost(string, tag = "3")]
    pub slug: ::prost::alloc::string::String,
    /// 文章摘要
    #[prost(string, tag = "4")]
    pub summary: ::prost::alloc::string::String,
    /// 文章内容 (Markdown)
    #[prost(string, tag = "5")]
    pub content: ::prost::alloc::string::String,
    /// 作者 ID
    #[prost(string, tag = "6")]
    pub author_id: ::prost::alloc::string::String,
    /// 标签列表
    #[prost(string, repeated, tag = "7")]
    pub tags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 浏览次数
    #[prost(int32, tag = "8")]
    pub view_count: i32,
    /// 点赞次数
    #[prost(int32, tag = "9")]
    pub like_count: i32,
    /// 文章状态
    #[prost(enumeration = "ArticleStatus", tag = "10")]
    pub status: i32,
    /// 创建时间
    #[prost(message, optional, tag = "11")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 更新时间
    #[prost(message, optional, tag = "12")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 发布时间
    #[prost(message, optional, tag = "13")]
    pub published_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 文章状态枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ArticleStatus {
    Unspecified = 0,
    Draft = 1,
    Published = 2,
    Archived = 3,
}
impl ArticleStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARTICLE_STATUS_UNSPECIFIED",
            Self::Draft => "ARTICLE_STATUS_DRAFT",
            Self::Published => "ARTICLE_STATUS_PUBLISHED",
            Self::Archived => "ARTICLE_STATUS_ARCHIVED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARTICLE_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "ARTICLE_STATUS_DRAFT" => Some(Self::Draft),
            "ARTICLE_STATUS_PUBLISHED" => Some(Self::Published),
            "ARTICLE_STATUS_ARCHIVED" => Some(Self::Archived),
            _ => None,
        }
    }
}
/// 获取用户请求
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户响应
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 用户信息
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    /// 用户唯一标识
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱地址
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "5")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 个人简介
    #[prost(string, tag = "6")]
    pub bio: ::prost::alloc::string::String,
    /// 创建时间
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 更新时间
    #[prost(message, optional, tag = "8")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
}
include!("luhanxin.community.v1.tonic.rs");
// @@protoc_insertion_point(module)