#!/usr/bin/env bash
# =============================================================
# gen-proto-mod.sh
# 在 buf generate 之后运行，自动生成 crates/shared/src/proto/mod.rs
# 扫描 prost 生成的 .rs 文件，构建嵌套 mod 结构 + re-export
# =============================================================
set -euo pipefail

PROTO_DIR="crates/shared/src/proto"
MOD_FILE="${PROTO_DIR}/mod.rs"

# 找到所有 prost 生成的 .rs 文件（排除 .tonic.rs，因为 prost 文件末尾会自动 include 它）
PROST_FILES=$(find "${PROTO_DIR}" -name '*.rs' ! -name '*.tonic.rs' ! -name 'mod.rs' | sort)

if [ -z "${PROST_FILES}" ]; then
  echo "⚠️  No prost-generated .rs files found in ${PROTO_DIR}"
  exit 0
fi

# 开始生成 mod.rs
cat > "${MOD_FILE}" << 'HEADER'
// @generated by scripts/gen-proto-mod.sh — DO NOT EDIT
// Proto 生成代码模块
// prost 生成的 .rs 文件末尾会自动 include 对应的 .tonic.rs 文件
// 因此只需 include prost 文件即可同时获得类型定义和 gRPC client/server

HEADER

# 收集所有需要的 mod 路径和 include 路径
declare -a MOD_PATHS=()
declare -a INCLUDE_PATHS=()

for file in ${PROST_FILES}; do
  # 获取相对于 PROTO_DIR 的路径，如 luhanxin/community/v1/luhanxin.community.v1.rs
  rel_path="${file#${PROTO_DIR}/}"
  dir_path=$(dirname "${rel_path}")
  filename=$(basename "${rel_path}")

  MOD_PATHS+=("${dir_path}")
  INCLUDE_PATHS+=("${rel_path}")
done

# 生成嵌套 mod 结构
# 对于路径 luhanxin/community/v1 生成:
#   pub mod luhanxin { pub mod community { pub mod v1 { include!(...) } } }

{
  echo "#[allow(clippy::all, clippy::pedantic)]"

  for i in "${!MOD_PATHS[@]}"; do
    mod_path="${MOD_PATHS[$i]}"
    include_path="${INCLUDE_PATHS[$i]}"

    # 拆分路径为模块层级
    IFS='/' read -ra PARTS <<< "${mod_path}"

    # 开启嵌套 mod
    for part in "${PARTS[@]}"; do
      echo "pub mod ${part} {"
    done

    # include 生成文件
    echo "    include!(\"${include_path}\");"

    # 关闭嵌套 mod（逆序）
    for ((j=${#PARTS[@]}-1; j>=0; j--)); do
      echo "}"
    done
  done

  echo ""
  echo "// Re-export：扁平化导出，使用时直接 \`use shared::proto::XxxRequest\` 即可"

  # 为每个模块路径生成 re-export
  for mod_path in "${MOD_PATHS[@]}"; do
    use_path=$(echo "${mod_path}" | sed 's|/|::|g')
    echo "pub use ${use_path}::*;"
  done
} >> "${MOD_FILE}"

echo "  → Generated ${MOD_FILE}"
